# This is a basic workflow to help you get started with Actions

name: branch management

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Environment variables for the workflow
  THE_FIRST_PLATFORM: "frontend"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run task
        run: echo Start branch management!

      # Runs a set of commands using the runners shell
      - name: Set up Git configuration
        run: |
          git config --global user.name "aiqubit"
          git config --global user.email "aiqubit@hotmail.com"

      - name: Create ${{env.THE_FIRST_PLATFORM}} branch
        run: |
          cd src/${{env.THE_FIRST_PLATFORM}}
          git init
          git add .
          git commit -m "Initial commit from ${{env.THE_FIRST_PLATFORM}}"
          git checkout -b ${{env.THE_FIRST_PLATFORM}}
          echo https://github.com/${{ github.repository }}
          echo ${{ env.GITHUB_TOKEN }}
          echo ${{ secrets.GITHUB_TOKEN }}
          git remote set-url origin https://github.com/${{ github.repository }}
          git push -u origin ${{env.THE_FIRST_PLATFORM}} -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create ${{env.THE_SECOND_PLATFORM}} branch
        run: |
          echo todo!         
